spring.application.name=orderapp
spring.main.banner-mode=OFF
logging.level.root=INFO
spring.datasource.url=jdbc:h2:mem:orderappdb
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.batch.job.enabled=false
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB